--
-- PostgreSQL database dump
-- Exported by Node.js ETL script
--
-- Database: sa_risk
-- Table: catalog.indicator
--

SET search_path TO catalog, public;

--
-- Data for Name: indicator; Type: TABLE DATA; Schema: catalog
--

INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (1, 'population_total', 'Total population', 'socio-economic', 'persons (raw count)', 'neutral', 'Census 2022 population (raw count)', 1, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (7, 'households_total', 'Number of households', 'socio-economic', 'households (raw count)', 'neutral', 'Census households (raw count)', NULL, 'indicator', 'Households', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (8, 'avg_household_size', 'Average household size', 'socio-economic', 'persons per household', 'neutral', 'People per household', NULL, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (9, 'dependency_ratio', 'Dependency ratio', 'socio-economic', 'dependents per 100 working-age persons', 'adverse', 'Dependents (0–14, 65+) per 100 working-age', NULL, 'indicator', 'Households', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (10, 'sex_ratio', 'Sex ratio', 'socio-economic', 'males per 100 females', 'neutral', 'Males per 100 females (ideal ≈100)', NULL, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (11, 'pct_children_0_14', 'Young children (0–14 years)', 'socio-economic', 'percent of population', 'neutral', 'Share of population aged 0–14', NULL, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (12, 'pct_working_age_15_64', 'Working age (15–64 years)', 'socio-economic', 'percent of population', 'beneficial', 'Share of population aged 15–64', NULL, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (13, 'pct_elderly_65plus', 'Elderly (65+ years)', 'socio-economic', 'percent of population', 'neutral', 'Share of population aged 65+', NULL, 'indicator', 'Demographics', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (14, 'pct_no_schooling_20plus', 'No schooling (20+ years)', 'socio-economic', 'percent of population 20+', 'adverse', 'Share of 20+ with no schooling', NULL, 'indicator', 'Education', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (15, 'pct_higher_edu_20plus', 'Higher education (20+ years)', 'socio-economic', 'percent of population 20+', 'beneficial', 'Share of 20+ with higher education', NULL, 'indicator', 'Education', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (16, 'pct_formal_dwelling', 'Formal dwellings', 'socio-economic', 'percent of households', 'beneficial', 'Share in formal dwellings', NULL, 'indicator', 'Living conditions', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (17, 'pct_flush_sewer', 'Flush toilets connected to sewerage', 'socio-economic', 'percent of households', 'beneficial', 'Households with flush toilets to sewer', NULL, 'indicator', 'Living conditions', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (18, 'pct_weekly_refuse', 'Weekly refuse disposal service', 'socio-economic', 'percent of households', 'beneficial', 'Households served weekly', NULL, 'indicator', 'Living conditions', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (19, 'pct_piped_water_dwelling', 'Access to piped water in the dwelling', 'socio-economic', 'percent of households', 'beneficial', 'Households with piped water in dwelling', NULL, 'indicator', 'Living conditions', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (20, 'pct_electricity_lighting', 'Electricity for lighting', 'socio-economic', 'percent of households', 'beneficial', 'Households using electricity for lighting', NULL, 'indicator', 'Living conditions', 'Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (21, 'hh_conditions_subindex', 'Household Conditions Sub-Index', 'socio-economic', 'composite score (0–100)', 'beneficial', 'Equal-weighted composite (0–100) summarising basic household service access: formal dwelling, flush/sewer connection, weekly refuse removal, piped water in the dwelling, and electricity for lighting. Each component is on a 0–100 scale (higher = better). Formula: SubIndex = (Σ w_i * x_i) / (Σ w_i) with w_i=1 and x_i∈[0,100]. Example: (80+60+70+50+90)/5=70.', 100, 'sub_index', 'Living conditions', 'Derived from Stats SA Census 2022', 'https://census.statssa.gov.za');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (24, 'crime_contact_total', 'Total Contact Crimes (Crimes against the person)', 'SAPS crime category', 'cases (raw count)', 'neutral', 'Total of contact crimes (SAPS definition).', 100, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (25, 'crime_murder', 'Murder', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Murder cases recorded by SAPS.', 101, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (26, 'crime_sexual_offences', 'Sexual offences (aggregate)', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Aggregate of sexual offences (rape, sexual assault, attempted sexual offences, contact sexual offences).', 102, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (27, 'crime_attempted_murder', 'Attempted murder', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Attempted murder cases.', 103, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (28, 'crime_assault_gbh', 'Assault with intent to inflict grievous bodily harm', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Assault GBH cases.', 104, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (29, 'crime_common_assault', 'Common assault', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Common assault cases.', 105, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (30, 'crime_common_robbery', 'Common robbery', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Common robbery cases.', 106, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (31, 'crime_robbery_aggrav', 'Robbery with aggravating circumstances', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Robbery with aggravating circumstances.', 107, 'indicator', 'Contact crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (32, 'crime_rape', 'Rape', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Rape cases recorded by SAPS.', 120, 'indicator', 'Sexual Offences', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (33, 'crime_sexual_assault', 'Sexual assault', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Sexual assault cases.', 121, 'indicator', 'Sexual Offences', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (34, 'crime_attempted_sexual_offences', 'Attempted sexual offences', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Attempted sexual offences.', 122, 'indicator', 'Sexual Offences', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (35, 'crime_contact_sexual_offences', 'Contact sexual offences', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Contact sexual offences.', 123, 'indicator', 'Sexual Offences', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (36, 'crime_total_sexual_offences', 'Total Sexual Offences', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Sum of sexual offence subcategories.', 124, 'indicator', 'Sexual Offences', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (37, 'crime_carjacking', 'Carjacking', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Motor vehicle hijacking (carjacking).', 140, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (38, 'crime_robbery_res', 'Robbery at residential premises', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Robbery at residential premises.', 141, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (39, 'crime_robbery_nonres', 'Robbery at non-residential premises', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Robbery at non-residential premises.', 142, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (40, 'crime_cash_in_transit', 'Robbery of cash in transit', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Cash-in-transit robbery.', 143, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (41, 'crime_bank_robbery', 'Bank robbery', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Bank robbery.', 144, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (42, 'crime_truck_hijacking', 'Truck hijacking', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Truck hijacking.', 145, 'indicator', 'Aggravated robbery', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (43, 'crime_contact_related_total', 'Total Contact-Related Crimes', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Total of contact-related crimes (SAPS definition).', 160, 'indicator', 'Contact-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (44, 'crime_arson', 'Arson', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Arson cases.', 161, 'indicator', 'Contact-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (45, 'crime_malicious_damage', 'Malicious damage to property', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Malicious damage to property.', 162, 'indicator', 'Contact-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (46, 'crime_property_related_total', 'Total Property-Related Crimes', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Total of property-related crimes (SAPS definition).', 180, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (47, 'crime_burglary_nonres', 'Burglary at non-residential premises', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Burglary at non-residential premises.', 181, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (48, 'crime_burglary_res', 'Burglary at residential premises', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Burglary at residential premises.', 182, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (49, 'crime_theft_vehicle', 'Theft of motor vehicle and motorcycle', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Theft of motor vehicle and motorcycle.', 183, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (50, 'crime_theft_from_vehicle', 'Theft out of or from motor vehicle', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Theft out of or from motor vehicle.', 184, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (51, 'crime_stock_theft', 'Stock-theft', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Stock-theft.', 185, 'indicator', 'Property-related crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (52, 'crime_other_serious_total', 'Total Other Serious Crimes', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Total of other serious crimes (SAPS definition).', 200, 'indicator', 'Other serious crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (53, 'crime_all_theft_other', 'All theft not mentioned elsewhere', 'SAPS crime category', 'cases (raw count)', 'adverse', 'All theft not mentioned elsewhere.', 201, 'indicator', 'Other serious crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (54, 'crime_commercial', 'Commercial crime', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Commercial crime.', 202, 'indicator', 'Other serious crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (55, 'crime_shoplifting', 'Shoplifting', 'SAPS crime category', 'cases (raw count)', 'adverse', 'Shoplifting.', 203, 'indicator', 'Other serious crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (56, 'crime_17_serious_total', 'Total 17 Community Reported Serious Crimes', 'SAPS crime category', 'cases (raw count)', 'adverse', 'SAPS “17 Community Reported Serious Crimes” total.', 220, 'indicator', 'Community Reported Serious Crimes', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (57, 'crime_detected_police_total', 'Total crime detected as a result of police action', 'SAPS crime category', 'cases (raw count)', 'neutral', 'Total of police-action-detected crimes (policing-sensitive).', 240, 'indicator', 'Crime detected as a result of police action', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (58, 'crime_illegal_firearms', 'Illegal possession of firearms and ammunition', 'SAPS crime category', 'cases (raw count)', 'neutral', 'Illegal possession of firearms and ammunition detected by police action.', 241, 'indicator', 'Crime detected as a result of police action', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (59, 'crime_drug_related', 'Drug-related crime', 'SAPS crime category', 'cases (raw count)', 'neutral', 'Drug-related crime detected by police action.', 242, 'indicator', 'Crime detected as a result of police action', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (60, 'crime_dui', 'Driving under the influence of alcohol or drugs', 'SAPS crime category', 'cases (raw count)', 'neutral', 'DUI cases detected by police action.', 243, 'indicator', 'Crime detected as a result of police action', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (61, 'crime_sexoff_detected', 'Sexual offences detected as a result of police action', 'SAPS crime category', 'cases (raw count)', 'neutral', 'Sexual offences detected via police action (policing-sensitive).', 244, 'indicator', 'Crime detected as a result of police action', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (100, 'crime_contact_subindex', 'Contact Crimes Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'adverse', 'Equal-weighted sub-index of contact crimes (murder, sexual offences, attempted murder, assault GBH, common assault, common robbery, robbery with aggravating circumstances). Each normalised to 0–100 scale, averaged.', 300, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (102, 'crime_sexual_subindex', 'Sexual Offences Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'adverse', 'Equal-weighted composite of: rape; sexual assault; attempted sexual offences; contact sexual offences.', 301, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (103, 'crime_aggrav_robbery_subindex', 'Aggravated Robbery Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'adverse', 'Equal-weighted composite of: carjacking; robbery at residential premises; robbery at non-residential premises; cash-in-transit robbery; bank robbery; truck hijacking.', 302, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (104, 'crime_property_subindex', 'Property-Related Crimes Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'adverse', 'Equal-weighted composite of: burglary non-residential; burglary residential; theft of motor vehicle & motorcycle; theft out of/from motor vehicle; stock-theft.', 303, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (105, 'crime_policeaction_subindex', 'Police-Action Detected Crimes Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'neutral', 'Equal-weighted composite of: illegal firearms & ammunition; drug-related crime; DUI; sexual offences detected via police action.', 304, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');
INSERT INTO catalog.indicator (id, key, label, category, unit, polarity, description, sort_order, measure_type, theme, source_name, source_url) VALUES (117, 'crime_police_action_subindex', 'Police-Action Sub-Index', 'SAPS crime sub-index', 'composite score (0–100)', 'neutral', 'Equal-weighted sub-index of policing-sensitive offences (illegal firearms, drug-related, DUI, sexual offences detected). Each normalised to 0–100, averaged.', 302, 'sub_index', 'Crime', 'South African Police Service (SAPS)', 'https://www.saps.gov.za/services/crimestats.php');

